[package]
name = "pls"
version = "0.1.0"
edition = "2021"
description = "oxidized helpy help"
license = "MIT"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
color-eyre = "0.6.5"
eyre = "0.6.12"
hostname = "0.4.2"
